default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: image_upload_development
  username: <%= ENV.fetch("PG_USERNAME") { 5 } %>

test:
  <<: *default
  database: image_upload_test
  username: <%= ENV.fetch("PG_USERNAME") { 5 } %>
